package at.ac.tuwien.model.change.management.git.operation;

import lombok.NonNull;

import java.util.Collection;
import java.util.Optional;

public interface VersionNameGenerator {

    String generateInitialVersionName();

    Optional<String> incrementVersionName(@NonNull String versionName);

    Optional<String> findMostRecentVersionName(@NonNull Collection<String> names);

    boolean isAutoGeneratedVersionName(@NonNull String versionName);

    default String findNextVersionName(@NonNull Collection<String> names) {
        return findMostRecentVersionName(names)
                .flatMap(this::incrementVersionName)
                .orElseGet(this::generateInitialVersionName);
    }
}
